### ISSUE TITLE
Should change dispose to unsubscribe

### ISSUE THREAD

**Issue by MaherSoua** [staltz/rxjs-training#5]
https://github.com/staltz/rxjs-training/blob/1b8bc43c0254e565dc7d3a163a924645940e6dca/04/solution/promise-vs-observable-2.js#L27

**Comment by staltz** [comment]
Hi @MaherSoua, thank you for taking your time to send us this issue. Note however that this material was written 3 years ago, before RxJS v5 was released. This was based on RxJS v4, which has dispose-based subscriptions.
